### ISSUE TITLE
Couldn't export Python operator _DCNv2

### ISSUE THREAD

**Issue by xiazi-yu** [dlunion/tensorRTIntegrate#10]
RuntimeError: ONNX export failed: Couldn't export Python operator _DCNv2

**Comment by dlunion** [comment]
[参照这里](https://github.com/dlunion/tensorRTIntegrate/tree/master/dcn_onnx)，对dcn特殊实现改动后导出。
还要[这里](https://github.com/dlunion/tensorRTIntegrate/blob/master/README.onnx.plugin.md)的文档，以及[这里](https://github.com/dlunion/tensorRTIntegrate/blob/master/plugin_onnx_export.py)的案例代码

**Comment by xiazi-yu** [comment]
我用dcn_onnx,把原来centernet的目录文件替换了，执行 python dladcn_export_onnx.py
Traceback (most recent call last):
  File "dladcn_export_onnx.py", line 27, in <module>
    onnx.export(model, (input), "dladcnv2.onnx", output_names=["hm", "wh", "reg", "hm_pool"], verbose=True)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 64, in export
    example_outputs=example_outputs, strip_doc_string=strip_doc_string, dynamic_axes=dynamic_axes)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 340, in _export
    params_dict, opset_version, dynamic_axes, defer_weight_export, operator_export_type, strip_doc_string)
RuntimeError: ONNX export failed: Couldn't export Python operator _DCNv2

还需要一些其他操作么，谢谢？

**Comment by xiazi-yu** [comment]
solve

**Comment by dlunion** [comment]
问题解决了吗？

**Comment by xiazi-yu** [comment]
没有解决，不清楚哪块不对

**Comment by xiazi-yu** [comment]
解决了

**Comment by piaoliuping123** [comment]
> 解决了

您好，我也遇到同样的情况，请问怎么做的？谢谢dalao

**Comment by mchl0203** [comment]
~Hi @dlunion @xiazi-yu :~
~我把 CenterNet 源码 models 下的DCNv2文件夹、dcn_v2.py、pose_dla_dcn.py 都替换成dcn_onnx下的文件及文件夹，然后添加了一行`sys.path.append("models")`, 但运行 dladcn_export_onnx.py 还是报错：~
~```RuntimeError: ONNX export failed: Couldn't export Python operator _DCNv2```~
~请问我是遗漏了什么操作吗~

不好意思，我的问题，没有把dcn_v2.py替换掉
