### ISSUE TITLE
vs2017 报未找到导入项目 BuildCustomizations\CUDA 10.0.props 错误

### ISSUE THREAD

**Issue by bigpo** [dlunion/tensorRTIntegrate#15]
我按照视频教程下载代码，并用vs2017打开，但是生成的时候报错，

> 严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB4019	未找到导入的项目“C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.0.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。	TensorRT	D:\github_prj\tensorRTIntegrate-master\TensorRT.vcxproj	128	

我看了下  `TensorRT.vcxproj` 第128行是： `<Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 10.0.props" />` 这个文件无法在vs安装目录或者是项目目录下找到。

请问这个问题该如何解决呢？

**Comment by bigpo** [comment]
我按照视频教程下载代码，并用vs2017打开，但是生成的时候报错，

> 严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB4019	未找到导入的项目“C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.0.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。	TensorRT	D:\github_prj\tensorRTIntegrate-master\TensorRT.vcxproj	128	

我看了下  `TensorRT.vcxproj` 第128行是： `<Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 10.0.props" />` 这个文件无法在vs安装目录或者是项目目录下找到。

请问这个问题该如何解决呢？

**Comment by hopef** [comment]
这是因为你的电脑没有安装cuda10，打开TensorRT.vcxproj第128行，把这个改成你对应的cuda版本，或者删掉。然后点击解决方案的右键，生成依赖项，生成自定义，选择一个你安装了的版本

**Comment by bigpo** [comment]
> 这是因为你的电脑没有安装cuda10，打开TensorRT.vcxproj第128行，把这个改成你对应的cuda版本，或者删掉。然后点击解决方案的右键，生成依赖项，生成自定义，选择一个你安装了的版本

感谢回复

我看视频讲解是说把所有依赖都放入到 项目中的 `lean` 文件夹下了。以为不需要外部的配置，但其实我有自己装cuda，系统环境变量配置的也有。 

按照你说的，我将 `TensorRT.vcxproj` 文件中的 `<Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 10.0.props" />` 删去（原因是我无法在系统中搜索到 CUDA 10.0.props文件，所以无法更改到对应的文件位置），并在项目中右键解决方案->生成依赖项->生成自定义，但给出的列表中并没有 cuda相关的选项。

不知道还有没有其他可以尝试的方案，再次感谢！

**Comment by hopef** [comment]
依赖确实在lean下，但是同时依赖一个cuda编译环境和插件

你很可能是先安装的cuda然后装的vs，导致没有导入cuda的vs集成环境支持。你可以考虑重新安装下cuda，有个visual studio integrate之类的插件安装选项

**Comment by bigpo** [comment]
> 依赖确实在lean下，但是同时依赖一个cuda编译环境和插件
> 
> 你很可能是先安装的cuda然后装的vs，导致没有导入cuda的vs集成环境支持。你可以考虑重新安装下cuda，有个visual studio integrate之类的插件安装选项

确实是这个原因，我重新安装cuda之后就好了，非常感谢！
