### ISSUE TITLE
linux上编译报错，用的是tensorrt6.0,cuda10.0

### ISSUE THREAD

**Issue by XuHao9166** [dlunion/tensorRTIntegrate#2]
plugin/plugins/DCNLayer.cu(248): error: more than one conversion function from "const halfloat" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"

**Comment by dlunion** [comment]
CUCC := nvcc -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_61,code=sm_61

**Comment by dlunion** [comment]
在Makefile的第四行，添加gencode定义。因为fp16需要更高的版本支持。抱歉这个漏掉了：
CUCC := nvcc -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_61,code=sm_61

**Comment by zjd1988** [comment]
@dlunion  那是不是说在jetson nano上就无法使用了呢，nano的compute capbility是5.3。但是nano官方介绍支持fp16，我后边测试下在nano下能否把这个工程跑起来。

**Comment by 205418367** [comment]
谁可以分享一个在ubuntu下编译的cmake文件？我想学习一下,本人用ubuntu
