### ISSUE TITLE
相比原本的函数为什么要传入个std::vector<nvinfer1::Dims>& dims呢？

### ISSUE THREAD

**Issue by BaofengZan** [dlunion/tensorRTIntegrate#27]
https://github.com/dlunion/tensorRTIntegrate/blob/7543614a4ff5f6e022526a4e137d47f4e63f5f96/src/onnx_parser/NvOnnxParser.h#L218
这里相对于原始的函数https://github.com/onnx/onnx-tensorrt/blob/84b5be1d6fc03564f2c0dba85a2ee75bad242c2e/NvOnnxParser.h#L239，
传入的dims作用是什么呢？ 动态batch？

**Comment by dlunion** [comment]
当你导出onnx时指定了input的shape是mxn的，那么你在tensorRT做编译转换的时候，输入的shape就被限制了，使用的必定是mxn

我增加的dims，是为了在tensorRT编译阶段修改这个shape为自己想要的大小，尤其是FCN那种，也可以不修改使用onnx导出时的

**Comment by BaofengZan** [comment]
ok，有点理解了 ，我在看一看
