### ISSUE TITLE
在 Ubuntu 下面怎么编译啊

### ISSUE THREAD

**Issue by Qjizhi** [dlunion/tensorRTIntegrate#33]
makefile 貌似有很多版本问题, 另外 LEAN 这个东西在Ubuntu 下面需要么, 不太了解? 请问你是怎么编译啊?

**Comment by Qjizhi** [comment]
修改了一些路径解决了.

**Comment by 205418367** [comment]
你是怎么解决的？我也想在ubuntu下面编译，求大佬指点一二！

**Comment by Qjizhi** [comment]
> 你是怎么解决的？我也想在ubuntu下面编译，求大佬指点一二！

这个项目应该是在windows 下的,就是makefile里的头文件和库文件的路径修改一下.

**Comment by gongdalinux** [comment]
@Qjizhi 修改了makefile的头文件和库文件，仍报一堆错。可以分享下makefile参考下不

**Comment by Qjizhi** [comment]
> @Qjizhi 修改了makefile的头文件和库文件，仍报一堆错。可以分享下makefile参考下不

`ECHO = @echo
OUTNAME = trtrun
CC := g++
CUCC := nvcc
SRCDIR := src
OBJDIR := objs
#LEAN := /datav/newbb/lean
LEAN := /usr/local
#BINDIR := $(LEAN)/tensorRTIntegrate
BINDIR := workspace
TENSORRT_NAME := /home/xxx/Downloads/TensorRT/TensorRT-7.0.0.11


#TENSORRT_NAME := TensorRT-6.0.1.8-cuda10.2-cudnn7.6
CFLAGS := -std=c++11 -fPIC -m64 -g -O3 -fopenmp -w -DONNX_ML -DNDEBUG 
CUFLAGS := -std=c++11 -m64 -Xcompiler -fPIC -g -O3 -w -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_61,code=sm_61


# INC_OPENCV := $(LEAN)/opencv3.4.1/include/opencv3
INC_OPENCV := $(LEAN)/include/opencv
INC_LOCAL := ./src ./src/builder ./src/common ./src/infer ./src/plugin ./src/plugin/plugins
# INC_SYS := /usr/local/protobuf/include
INC_SYS := $(LEAN)/include/google/protobuf
INC_CUDA := $(LEAN)/cuda-10.0/include $(TENSORRT_NAME)/include $(LEAN)/cudnn7.6.5.32-cuda10.2
INCS := $(INC_SYS) $(INC_OPENCV) $(INC_LOCAL) $(INC_CUDA)
INCS := $(foreach inc, $(INCS), -I$(inc))

LIB_CUDA := $(LEAN)/cuda-10.0/lib64  $(TENSORRT_NAME)/lib $(LEAN)/cudnn7.6.5.32-cuda10.2
# LIB_SYS := /usr/local/protobuf/lib
LIB_SYS := $(LEAN)/lib
# LIB_OPENCV := $(LEAN)/opencv4.2.0/lib 
LIB_OPENCV := $(LEAN)/lib
LIBS := $(LIB_SYS) $(LIB_CUDA) $(LIB_OPENCV)
LIBS := $(foreach lib, $(LIBS),-L$(lib))

RPATH := $(LIB_SYS) $(LIB_CUDA) $(LIB_OPENCV)
RPATH := $(foreach lib, $(RPATH),-Wl,-rpath=$(lib))

LD_OPENCV := opencv_core opencv_highgui opencv_imgproc opencv_video opencv_videoio opencv_imgcodecs
LD_NVINFER := nvinfer nvinfer_plugin nvparsers
LD_CUDA := cuda curand cublas cudart cudnn
LD_SYS := stdc++
LDS := $(LD_SYS) $(LD_OPENCV) $(LD_NVINFER) $(LD_CUDA)
LDS := $(foreach lib, $(LDS), -l$(lib))

SRCS := $(shell cd $(SRCDIR) && find -name "*.cpp")
OBJS := $(patsubst %.cpp,%.o,$(SRCS))
OBJS := $(foreach item,$(OBJS),$(OBJDIR)/$(item))
CUS := $(shell cd $(SRCDIR) && find -name "*.cu")
CUOBJS := $(patsubst %.cu,%.o,$(CUS))
CUOBJS := $(foreach item,$(CUOBJS),$(OBJDIR)/$(item))
OBJS := $(subst /./,/,$(OBJS))
CUOBJS := $(subst /./,/,$(CUOBJS))

all: $(BINDIR)/$(OUTNAME)
	$(ECHO) Done, now you can run this program with \"make run\" command.

run: all
	@cd $(BINDIR) && ./$(OUTNAME)

$(BINDIR)/$(OUTNAME): $(OBJS) $(CUOBJS)
	$(ECHO) Linking: $@
	@g++  $(LIBS) -o $@ $^ $(LDS) $(RPATH) -pthread -lprotobuf 

$(CUOBJS) : $(OBJDIR)/%.o : $(SRCDIR)/%.cu
	@if [ ! -d $@ ]; then mkdir -p $(dir $@); fi
	$(ECHO) Compiling: $<
	@$(CUCC) $(CUFLAGS) $(INCS) -c -o $@ $<

$(OBJS) : $(OBJDIR)/%.o : $(SRCDIR)/%.cpp
	@if [ ! -d $@ ]; then mkdir -p $(dir $@); fi
	$(ECHO) Compiling: $<
	@$(CC) $(CFLAGS) $(INCS) -c -o $@ $<

clean:
	rm -rf $(OBJDIR) $(BINDIR)/$(OUTNAME)
`
